### ISSUE TITLE
 Could NOT find OpenSSL

### ISSUE THREAD

**Issue by pythrick** [dougg3/obs-ios-camera-source#9] opened 2021-04-05 13:29 UTC
Hi folks, I've been trying to install it using `yay` on Manjaro, but I'm stuck with the following error:

```
CMake Error at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1j")
Call Stack (most recent call first):
  /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.19/Modules/FindOpenSSL.cmake:536 (find_package_handle_standard_args)
  deps/libimobiledevice/CMakeLists.txt:5 (find_package)
```

I've already installed `openssl` and a bunch of other things, exported the system variables pointing to open ssl directories, but still I have no clue about what I'm suppose to do to make this works.

**Comment by dougg3** [comment] 2021-04-05 14:12
Hi! I ran into a similar problem trying to get it working on Arch for testing. I’m not familiar with Manjaro but it sounds like it’s based on Arch. Make sure you have any OpenSSL development package installed. Also make sure you have the OpenSSL static libraries installed because it links statically. On Arch these packages are called `openssl-devel` and `openssl-static`.

**Comment by dougg3** [comment] 2021-04-10 18:13
I think I got Arch and Fedora mixed up in my mind when I made that last comment, my bad. But...I dinked around a bit in Arch again and reproduced the problem you mentioned when I attempted to install through `yay`.

The problem is that one of the recent upstream changes added a dependency on libimobiledevice, and for some silly reason, it's linking statically against OpenSSL instead of dynamically. Arch doesn't provide static builds of OpenSSL. There is an AUR package called openssl-static, but I tried to install it and it doesn't work.

What I'm going to do is change our local copy of libimobiledevice to link dynamically against OpenSSL instead of statically. There's no need for linking statically, especially on Linux, and it seems to cause headaches for people.

**Comment by dougg3** [comment] 2021-04-10 18:24
This should be fixed now. Thanks for letting me know!

I just tested and installing through `yay` works now. For some reason it looks like maybe the locale file isn't being put in the proper place though, but that's an issue to fix in the AUR rather than this project.

**Closed as completed by dougg3** 2021-04-10 18:24 UTC
